### ISSUE TITLE
option to set the path to ssh key

### ISSUE THREAD

**Issue by slatunje** [kapilt/juju-digitalocean#29]
currently it is assumed the ssh key will be found in ~/.ssh/id_rsa.pub 

I happen to have three ssh keys: 

~/.ssh/id_rsa.pub 
~/.ssh/CompanyA/id_rsa.pub 
~/.ssh/CompanyB/id_rsa.pub 

It would be nice to be able to set the path to ssh key. the benefit is that companyA and companyB can also use juju-digitalocean

**Comment by chuckbutler** [comment]
Commenting to add some bug heat here, just had a user land in #juju with this issue on OSX.

**Comment by travenasty** [comment]
That user was me. :)

**Comment by kapilt** [comment]
the plugin doesn't touch any keys. this is more about juju' config for ssh keys, or how you have ssh configured. ssh will sniff and try a number of keys when logging into remote systems,  you can explicitly specify a private key on the cli, or via using an agent. as juju is the one invoking ssh, you have to configure an explicit private key in enviroments.yaml or ssh key agent via environment variable.

**Comment by kapilt** [comment]
rephrased, this is about the user configuring environment ssh keys via juju in their juju environments.yaml configuration. do plugin simply consumes that config invokes juju where needed atm.
