### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by ethernyEonian** [kapilt/juju-digitalocean#34]
Hi, when i try to use boostrap with only DO_OAUTH_TOKEN i have an error : 
Configuration error: Missing digital ocean api credentials

But if i take your last git code version and install manually all work fine only if i put my DO_OAUTH_TOKEN in provider.py

Thanks for your update.

**Comment by ethernyEonian** [comment]
Sorry it's working just forget to export env variable.

**Comment by kapilt** [comment]
added some more features to speed up machine provisioning, also there was some debug print i think when you tried it out which is also cleaned up. there's a new dependency on python jujuclient library.
